name: community_impact_tracker
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  image_picker: ^1.1.2
  file_picker: ^8.1.7
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.6.1
  firebase_storage: ^12.3.6
  path_provider: ^2.1.5
  intl: ^0.20.1 
  provider: ^6.1.2 
  google_maps_flutter: ^2.10.0
  dio: ^5.7.0
  flutter_polyline_points: ^2.1.0
  geolocator: ^13.0.3
  geocoding: ^3.0.0
  rxdart: ^0.28.0
  cloud_functions: ^5.3.3
  table_calendar: ^3.2.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.7
  image_cropper: ^9.1.0
  lottie: ^3.3.1
  flutter_launcher_icons: ^0.14.3
  saver_gallery: ^4.0.1
  flutter_heatmap_calendar: ^1.0.5
  blur: ^4.0.2
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  android: true
  ios: true
  image_path: "assets/GoodTrack_logo.png"


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/hourglass.json
    - assets/animations/navbar_icons/home.json
    - assets/animations/navbar_icons/shop.json
    - assets/animations/navbar_icons/leaderboard.json
    - assets/animations/navbar_icons/profile.json
    - assets/animations/appbar_icons/settings.json
    - assets/animations/appbar_icons/my_events_archive.json
    - assets/animations/appbar_icons/favorites.json
    - assets/animations/appbar_icons/cart.json
    - assets/animations/appbar_icons/notifications.json
    - assets/animations/appbar_icons/calendar.json
    - assets/animations/appbar_icons/filter.json
    - assets/animations/search.json
    # - assets/animations/search2.json
    - assets/images/Facebook.png
    - assets/images/Google.png

  shaders:
    - assets/shaders/moving_gradient.frag

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
